//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace PR.Chat.DAL.EF
{
    public partial class Account
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Login
        {
            get;
            set;
        }
    
        public virtual string PasswordHash
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedAt
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Nick> Nicks
        {
            get
            {
                if (_nicks == null)
                {
                    var newCollection = new FixupCollection<Nick>();
                    newCollection.CollectionChanged += FixupNicks;
                    _nicks = newCollection;
                }
                return _nicks;
            }
            set
            {
                if (!ReferenceEquals(_nicks, value))
                {
                    var previousValue = _nicks as FixupCollection<Nick>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNicks;
                    }
                    _nicks = value;
                    var newValue = value as FixupCollection<Nick>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNicks;
                    }
                }
            }
        }
        private ICollection<Nick> _nicks;

        #endregion
        #region Association Fixup
    
        private void FixupNicks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Nick item in e.NewItems)
                {
                    item.Account = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Nick item in e.OldItems)
                {
                    if (ReferenceEquals(item.Account, this))
                    {
                        item.Account = null;
                    }
                }
            }
        }

        #endregion
    }
}
