//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace PR.Chat.DAL.EF
{
    public partial class ChatDB : ObjectContext
    {
        public const string ConnectionString = "name=ChatDB";
        public const string ContainerName = "ChatDB";
    
        #region Constructors
    
        public ChatDB()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ChatDB(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ChatDB(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<Channel> Channels
        {
            get { return _channels  ?? (_channels = CreateObjectSet<Channel>("Channels")); }
        }
        private ObjectSet<Channel> _channels;
    
        public ObjectSet<Messages> Messages
        {
            get { return _messages  ?? (_messages = CreateObjectSet<Messages>("Messages")); }
        }
        private ObjectSet<Messages> _messages;
    
        public ObjectSet<Nick> Nicks
        {
            get { return _nicks  ?? (_nicks = CreateObjectSet<Nick>("Nicks")); }
        }
        private ObjectSet<Nick> _nicks;

        #endregion
    }
}
