//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace PR.Chat.DAL.EF
{
    public partial class Nick
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int AccountID
        {
            get { return _accountID; }
            set
            {
                if (_accountID != value)
                {
                    if (Account != null && Account.Id != value)
                    {
                        Account = null;
                    }
                    _accountID = value;
                }
            }
        }
        private int _accountID;
    
        public virtual byte[] SettingsBinary
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedAt
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;

        #endregion
        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.Nicks.Contains(this))
            {
                previousValue.Nicks.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.Nicks.Contains(this))
                {
                    Account.Nicks.Add(this);
                }
                if (AccountID != Account.Id)
                {
                    AccountID = Account.Id;
                }
            }
        }

        #endregion
    }
}
